---
- hosts: dev
  become: True
  tasks:
    - name: update cache
      apt:
        update_cache: yes
    - name: pip install
      apt:
        name: python3-pip
        state: present
    - name: Install docker-py module
      pip:
        name: docker-py
        state: present
    - name: start the docker container
      docker_container:
        name: realme
        image: "2222s/realmeV-8"
        state: started
        published_ports:
          - 0.0.0.0:84:8080
          - 0.0.0.0:85:8080
